export interface EnneagramType {
  name: string;
  alias: string;
  coreFear: string;
  coreDesire: string;
  description: string;
  deepDive: string;
  strengths: string[];
  atBest: string;
  underStress: string;
  growthPath: string;
  mantra: string;
  wing1: number;
  wing2: number;
}

export const ENNEAGRAM_TYPES: Record<number, EnneagramType> = {
  1: {
    name: 'The Reformer',
    alias: 'The Perfectionist',
    coreFear: 'Being corrupt, defective, or wrong',
    coreDesire: 'To be good, virtuous, and right',
    description: 'Principled, purposeful, and self-controlled. Ones hold themselves and others to high standards, driven by a deep inner critic and a genuine desire to improve the world.',
    deepDive: "You have an internal rulebook so finely tuned it practically has footnotes. The secret no one tells Type 1s: the inner critic isn't your conscience — it's fear wearing a clipboard. The real you, underneath all the standards, just wants the world to be good. That impulse is beautiful. Let it breathe.",
    strengths: ['Integrity', 'Discernment', 'Diligence'],
    atBest: 'Wise, noble, discerning, and profoundly principled',
    underStress: 'Critical, rigid, judgmental of self and others',
    growthPath: 'Move toward the spontaneity of Type 7 — allow yourself to be imperfect and still worthy.',
    mantra: 'I am good enough, as I am, right now.',
    wing1: 9,
    wing2: 2,
  },
  2: {
    name: 'The Helper',
    alias: 'The Giver',
    coreFear: 'Being unloved or unwanted',
    coreDesire: 'To feel loved and needed',
    description: 'Caring, interpersonal, and generous. Twos put the needs of others first, cultivating deep connections — sometimes at the cost of their own unspoken needs.',
    deepDive: "You've probably given things you didn't have to give, to people who didn't always notice. Here's your secret: the helping isn't selfless — not because you're calculating, but because love and need got tangled very early for you. The transformation arrives when you discover that you are worth showing up for, too.",
    strengths: ['Empathy', 'Warmth', 'Generosity'],
    atBest: 'Unconditionally loving, nurturing, and deeply supportive',
    underStress: 'Possessive, people-pleasing, and quietly resentful',
    growthPath: 'Move toward the self-care and authenticity of Type 4 — honor your own needs as sacred.',
    mantra: 'I receive love as freely as I give it.',
    wing1: 1,
    wing2: 3,
  },
  3: {
    name: 'The Achiever',
    alias: 'The Performer',
    coreFear: 'Being worthless or without value',
    coreDesire: 'To feel valuable and admired',
    description: 'Adaptive, success-oriented, and image-conscious. Threes are driven to excel and shape themselves to what success looks like in their environment.',
    deepDive: "You are so fluent at becoming what a room needs that sometimes you forget what you are when no one's watching. That's the real work for Type 3: not the next win, but the question of who celebrates with you when no one's evaluating. The performance is not the problem. The belief that you need it to be loved — that's the knot to untangle.",
    strengths: ['Ambition', 'Charisma', 'Efficiency'],
    atBest: 'Authentic, inspiring, a true role model for others',
    underStress: 'Competitive, image-driven, prone to deception',
    growthPath: 'Move toward the depth and loyalty of Type 6 — find your worth outside achievement.',
    mantra: 'I am loved for who I am, not what I accomplish.',
    wing1: 2,
    wing2: 4,
  },
  4: {
    name: 'The Individualist',
    alias: 'The Romantic',
    coreFear: 'Having no identity or personal significance',
    coreDesire: 'To find themselves and their unique identity',
    description: 'Expressive, dramatic, and self-aware. Fours live deeply in their inner world, seeking authenticity and beauty while mourning what feels perpetually out of reach.',
    deepDive: "You carry a longing so specific it's almost beautiful — the sense that something essentially you is perpetually just out of reach. Here's the secret: what you're looking for isn't out there. The Four who arrives is the one who discovers that the longing itself was the signal, not the problem. You weren't waiting to be found. You already are.",
    strengths: ['Depth', 'Creativity', 'Emotional honesty'],
    atBest: 'Profoundly creative, introspective, and compassionate',
    underStress: 'Withdrawn, melancholic, envious of others',
    growthPath: 'Move toward the groundedness of Type 1 — translate your depth into action.',
    mantra: 'I am whole in this moment, exactly as I am.',
    wing1: 3,
    wing2: 5,
  },
  5: {
    name: 'The Investigator',
    alias: 'The Observer',
    coreFear: 'Being overwhelmed or incompetent',
    coreDesire: 'To be capable, competent, and knowledgeable',
    description: 'Perceptive, innovative, and private. Fives gather information and conserve energy, preferring the inner world of ideas to the demands of other people.',
    deepDive: "You watch more than you speak, and you know more than you say. This is not withholding — it's calibration. Type 5 understands intuitively that presence has a cost, so you spend it carefully. Your secret: the detachment is not disinterest. It's protection for something very tender underneath. The world is richer when you let people in, even a little.",
    strengths: ['Insight', 'Focus', 'Independent thinking'],
    atBest: 'Visionary, open-hearted, and pioneering in thought',
    underStress: 'Detached, isolated, cynical',
    growthPath: "Move toward the confidence of Type 8 — share what you know before it's perfect.",
    mantra: 'I have enough, know enough, am enough.',
    wing1: 4,
    wing2: 6,
  },
  6: {
    name: 'The Loyalist',
    alias: 'The Skeptic',
    coreFear: 'Being without support or guidance',
    coreDesire: 'To have security and feel supported',
    description: 'Committed, responsible, and anxious. Sixes are loyal to people and systems they trust, always scanning for what could go wrong — often their own fiercest advocates.',
    deepDive: "You've thought through the disaster scenarios so thoroughly that when things actually go wrong, you're the calmest person in the room — because you've already been there, in your head, a hundred times. Your secret: the anxiety isn't weakness. It's loyalty to the people and systems you love. The work is learning that you don't have to earn safety. You deserve it simply by being.",
    strengths: ['Loyalty', 'Responsibility', 'Courage'],
    atBest: 'Courageous, self-reliant, and deeply trustworthy',
    underStress: 'Anxious, suspicious, and reactively defensive',
    growthPath: 'Move toward the optimism of Type 9 — trust that it will be okay before you have proof.',
    mantra: 'I am safe, even in uncertainty.',
    wing1: 5,
    wing2: 7,
  },
  7: {
    name: 'The Enthusiast',
    alias: 'The Epicure',
    coreFear: 'Being deprived or trapped in pain',
    coreDesire: 'To be satisfied, content, and fulfilled',
    description: 'Spontaneous, fun-loving, and versatile. Sevens keep their options open, chasing pleasure and stimulation to avoid deeper pain or limitation.',
    deepDive: "You are the most optimistic person in the room — and also, quietly, one of the most afraid. Not of things, but of the feeling underneath things. Type 7's superpower is reframing; the shadow is that reframing can become escape. The gift arrives when you discover that presence — even with discomfort — is its own kind of freedom.",
    strengths: ['Enthusiasm', 'Optimism', 'Versatility'],
    atBest: 'Grateful, focused, joyful, and deeply present',
    underStress: 'Scattered, impulsive, escapist',
    growthPath: 'Move toward the focus of Type 5 — let the experience complete before chasing the next.',
    mantra: 'The present moment contains everything I need.',
    wing1: 6,
    wing2: 8,
  },
  8: {
    name: 'The Challenger',
    alias: 'The Protector',
    coreFear: 'Being controlled or harmed by others',
    coreDesire: 'To protect themselves and be self-reliant',
    description: 'Powerful, decisive, and confrontational. Eights assert themselves boldly, protect those they love fiercely, and refuse to show vulnerability.',
    deepDive: "You were made large — in voice, in presence, in appetite for truth. Type 8 doesn't manipulate; you confront. And somewhere you decided that vulnerability was the thing that got you hurt, so you traded it for armor. Your secret: the tenderness you protect so fiercely is not a liability. It is the source of all your power. The strongest thing you could do is let someone see it.",
    strengths: ['Confidence', 'Decisiveness', 'Protective instinct'],
    atBest: 'Heroic, magnanimous, and empowering to others',
    underStress: 'Domineering, aggressive, and controlling',
    growthPath: 'Move toward the openness of Type 2 — let the softness be the strength.',
    mantra: 'I am strong enough to be soft.',
    wing1: 7,
    wing2: 9,
  },
  9: {
    name: 'The Peacemaker',
    alias: 'The Mediator',
    coreFear: 'Loss and fragmentation — conflict that tears things apart',
    coreDesire: 'To have inner peace and harmony with the world',
    description: "Receptive, reassuring, and agreeable. Nines seek harmony above all, often merging with others' agendas and losing sight of their own desires and priorities.",
    deepDive: "You have the rarest gift: the ability to see every side so clearly that conflict dissolves in your presence. The shadow is that you can see every side so clearly that you forget which one is yours. Type 9's real work: your peace is not the same as harmony with everyone else. You are allowed to want things. You are allowed to be present — loudly, undeniably present.",
    strengths: ['Calmness', 'Acceptance', 'Natural mediation'],
    atBest: 'Peaceful, healing, grounding, and deeply supportive',
    underStress: 'Disengaged, complacent, and emotionally numb',
    growthPath: 'Move toward the purposeful action of Type 3 — let your presence be known.',
    mantra: 'My voice matters. I am here.',
    wing1: 8,
    wing2: 1,
  },
};
